ungrouped:
  hosts:
    server-1:
      ansible_connection: 
      ansible_host: 188.245.100.59
      ansible_password: 
      ansible_port: 
      ansible_private_key_file: true
      ansible_timeout: 
      ansible_user: root
      ansible_winrm_scheme: https
      bastion_certificate: 
      bastion_host_key: 
      bastion_password: 
      bastion_private_key: 

